### ISSUE TITLE
Err encountered when doing yarn add:module

### ISSUE THREAD

**Issue by itsvicsoto** [mikemajesty/monorepo-nestjs-cli#1]
```
~/sleek-base on  master ⌚ 12:17:12
$ yarn add:module
yarn run v1.22.18
$ monorepo-nestjs-cli --module
(node:89513) UnhandledPromiseRejectionWarning: Error: Error: Command failed: /Users/itsvicsoto/.nvm/versions/node/v14.19.1/lib/node_modules/@mikemajesty/monorepo-nestjs-cli/node_modules/node-file-dialog/python/dist -d
/bin/sh: /Users/itsvicsoto/.nvm/versions/node/v14.19.1/lib/node_modules/@mikemajesty/monorepo-nestjs-cli/node_modules/node-file-dialog/python/dist: is a directory

    at /Users/itsvicsoto/.nvm/versions/node/v14.19.1/lib/node_modules/@mikemajesty/monorepo-nestjs-cli/node_modules/node-file-dialog/index.js:35:16
    at ChildProcess.exithandler (child_process.js:390:5)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at Pipe.<anonymous> (net.js:686:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:89513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:89513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.25s.
```

Using nvm 14.19.1

**Comment by mikemajesty** [comment]
try with v14.18.1, It seens a bug, I'will fix it.

**Comment by mikemajesty** [comment]
Thaks for report, try with v14.18.1, It seens a bug, I'will fix it. :)

**Comment by mikemajesty** [comment]
![Screenshot from 2022-08-20 20-59-01](https://user-images.githubusercontent.com/11630212/185769843-0df15627-f1fe-44e8-8412-7c979b60421a.png)
